# Generated by Django 4.2.13 on 2024-07-27 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("dni", models.IntegerField()),
                ("address", models.CharField(default="", max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(default=8, max_length=8)),
                ("pets", models.JSONField(blank=True, default=dict, null=True)),
                ("pub_date", models.DateTimeField(verbose_name="Date Published")),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("breed", models.CharField(default="", max_length=200)),
                ("age", models.IntegerField(default=100)),
                ("vaccines", models.JSONField(blank=True, default=dict, null=True)),
                ("pub_date", models.DateTimeField(verbose_name="Date Published")),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myvet.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="VaccineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "pet_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myvet.pettype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vaccine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_date", models.DateTimeField(verbose_name="Application Date")),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myvet.pet"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myvet.vaccinetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField(default=100)),
                ("img", models.ImageField(max_length=10000, upload_to="")),
                ("pub_date", models.DateTimeField(verbose_name="Date Published")),
                (
                    "pet_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myvet.pettype"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myvet.producttype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pet",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myvet.pettype"
            ),
        ),
    ]
