# Generated by Django 4.2.13 on 2024-07-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myvet", "0002_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="surname",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
