# Generated by Django 4.2.13 on 2024-07-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myvet", "0003_client_surname_alter_client_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="password",
            field=models.CharField(default=""),
        ),
    ]
