# Generated by Django 4.2.13 on 2024-07-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myvet", "0005_client_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="dni",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_login",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Last Login"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="password",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="client",
            name="pub_date",
            field=models.DateTimeField(default=None, verbose_name="Date Published"),
        ),
    ]
