# Generated by Django 4.2.13 on 2024-07-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myvet", "0007_alter_client_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
