# Generated by Django 4.2.13 on 2024-08-02 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myvet", "0008_client_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="is_active",
        ),
        migrations.AddField(
            model_name="client",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="client",
            name="phone",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Appointment Date"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Published"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Published"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Published"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Published"
            ),
        ),
    ]
