# Generated by Django 4.2.13 on 2024-08-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myvet", "0010_alter_client_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="pets",
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="vaccines",
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
